name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: Dilipkumar1127/sampleworkflow/.github/workflows/gitactiondemo.yml@main
    # https://github.com/Dilipkumar1127/sampleworkflow.git
    # /Users/dilipkumardonka/Desktop/git-workflow/sampleworkflow/.github/workflows/gitactiondemo.yml
    