name: GitHub Actions Demo
on:
  push:
    branches: [ "main" ] 
  # workflow_call:
    # inputs: 
    #   cdkVersion:
    #     default: 2.x
    #     description: what version cdk is 
    #     type: string
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing build "
      - name: cdk install 
        run: npm install -g aws-cdk
      - name: buildCommand
        run: cdk synth --app ""