name: GitHub Actions Demo
on:
  workflow_dispatch:
    inputs:
      CompressArtifacts:
        default: true 
        description: Whether to compress or not the Artifact
        type: boolean  
      # Compresscommand:
      #   default:  tar -cvf my_file.tar my_file.txt 
      #   description: Command to compress th eartifact
      ArtifactPath:
         default: 
         type: string
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing build"
      
      - name: cdk install 
        run: npm install -g aws-cdk@2.x
      
      - name: working directory 
        run: pwd
      
      - name: zip file 
        run: cd .. ; tar -cvf sampleworkflow.tar sampleworkflow 
      
      - name: listing 
        run: ls -R
      
      - name: Create a file 
        run: echo "Sample to Upload artifact" > ${{inputs.ArtifactPath}}.txt

      - name: If Compressing file is True
        # if: ${{ inputs.CompressArtifacts == true }}
        run: tar -cvf ${{ inputs.ArtifactPath }}.tar ${{ inputs.ArtifactPath }}.txt 

      # - name: If Compressing file is False
      #   if: ${{ inputs.CompressArtifacts == false }}
      #   run: echo "Compression is not required"
      
      - name: 'Upload Compressed Artifact'
        uses: actions/upload-artifact@v3
        if: ${{ ( inputs.ArtifactPath ) && ( inputs.CompressArtifacts == true ) }}
        with:
          name: ${{ inputs.ArtifactPath }}.tar
          path: ./
          retention-days: 5
      - name: 'Upload UnCompressed Artifact'
        uses: actions/upload-artifact@v3
        if: ${{ ( inputs.ArtifactPath ) && ( inputs.CompressArtifacts == false ) }}
        with:
          name: ${{ inputs.ArtifactPath }}
          path: ./
          retention-days: 5