name: GitHub Actions Demo
on: [push]

inputs: 
  cdkVersion:
    default: 2.x
    description: what version cdk is 
    type: string
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing build "
      
      - name : cdk install 
        run: npm -i -g aws-cdk@{{ inputs.cdkVersion }}
        run: cdk synth