name: GitHub Actions Demo
on:
  push:
    branches: [ "main" ] 
  # workflow_call:
    # inputs: 
    #   cdkVersion:
    #     default: 2.x
    #     description: what version cdk is 
    #     type: string
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing build "
      - name: cdk install 
        run: npm install -g aws-cdk@2.x
      - name: working directory 
        run: pwd
      # - name: buildCommand
      #   run: cdk synth
      - name: zip file 
        run: cd .. ; zip -r sampleworkflow.zip sampleworkflow 
      - name: listing 
        run: ls
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: sampleworkflow.zip
          path: /home/runner/work/sampleworkflow/sampleworkflow
          retention-days: 5