name: GitHub Actions Demo
on:
  workflow_dispatch:
    inputs:
      CompressArtifacts:
        default: true 
        description: Whether to compress or not the Artifact
        type: boolean  
      # Compresscommand:
      #   default:  tar -cvf my_file.tar my_file.txt 
      #   description: Command to compress th eartifact
      ArtifactName:
         default: artifact
         type: string
      # ArtifactName2:
      #    default: 
      #    type: string
      WorkingDir:
         default: '.'
         type: string
         description: specify start dir
      ArtifactPath:
         default: Downloads
         description: path of Artifact
         type: string
      DownloadArtifact:
        default: true 
        description: Whether to Download or not the Artifact
        type: boolean
      
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing build"
      
      - name: cdk install 
        run: npm install -g aws-cdk@2.x
      
      - name: working directory 
        run: pwd
      
      # - name: zip file 
      #   run: cd .. ; tar -cvf sampleworkflow.tar sampleworkflow 
      
      - name: listing 
        run: ls -R
      
      - name: Create a file 
        run: echo "Sample to Upload artifact" > ${{ inputs.ArtifactName }}

      - name: If Compressing file is True
        if: ${{ inputs.CompressArtifacts == true }}
        run: tar -cvf ${{ inputs.ArtifactName }}.tar ${{inputs.WorkingDir}}
      # - name: If Compression not required  
      #   if: ${{ inputs.CompressArtifacts != true }}
      #   run: echo "Compression is not required"
      - name: If Downloading is True
        if: ${{ inputs.DownloadArtifact == true }}
        run: tar -xvf ${{ inputs.ArtifactName }}.tar ${{inputs.WorkingDir}} #/${{inputs.ArtifactPath}}
      # - name: If Compression not required  

      - name: listing files 
        run: ls

      # - name: If Compressing file is False
      #   if: ${{ inputs.CompressArtifacts == false }}
      #   run: echo "Compression is not required"
      # retention-days: 5
      
      - name: 'Upload Compressed Artifact'
        uses: actions/upload-artifact@v3
        if: ${{ ( inputs.ArtifactName ) && ( inputs.CompressArtifacts == true ) }}
        # if: ${{ inputs.ArtifactName  }}
        with:
          name: ${{ inputs.ArtifactName }}
          path: ${{ inputs.ArtifactName }}.tar
          retention-days: 5
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        if: ${{ ( inputs.ArtifactPath ) && ( inputs.CompressArtifacts != true ) }}
        # if: ${{ inputs.ArtifactPath }}
        with:
          name: ${{ inputs.ArtifactName }}
          path: ${{ inputs.WorkingDir }}/${{ inputs.ArtifactName }}
          retention-days: 5

      - name: Download artifact A
        uses: actions/download-artifact@v3
        if: ${{ ( inputs.ArtifactName ) && (inputs.DownloadArtifact == true) }}
        with:
          name: ${{ inputs.ArtifactName }}
          path: ${{ inputs.WorkingDir }}/${{ inputs.ArtifactPath }}

      